// "use client";

import { Cairo } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";
import Footer from "./Components/Footer";
const cairo = Cairo({ subsets: ["latin"], weight: ["400", "600", "700"] });


export const metadata = {
  title: "UM-Unlcker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={cairo.className}
      >
        <Header />

          {children}
        <Footer />
      </body>
    </html>
  );
}
